### ISSUE TITLE
Implement "slider" delegate for numeric properties

### ISSUE THREAD

**Issue by lexxmark** [lexxmark/QtnProperty#10]
Something like in the GIMP
![image](https://cloud.githubusercontent.com/assets/6108224/12427194/0a67b1dc-be9b-11e5-88a4-ca1b0595d002.png)

**Comment by kmkolasinski** [comment]
Perfect I would like to have something like that :) How to use it?

**Comment by lexxmark** [comment]
I've implemented 1st draft of "SliderBox" delegate for Float property. Please try it.
You can change property value by keyboard only now. I used "+" and "-" keys to increase and decrease values. Arrow up/down/left/right keys are reserved to navigation between properties. I think it's not a good idea to override them. Mouse manipulation is on the go.

![image](https://cloud.githubusercontent.com/assets/6108224/12441981/82aacfbc-bf09-11e5-836a-b707e432f7ca.png)

fillColor attribute is optional - in case you want have different colors for different properties.

```
    Float FloatPropertySliderBox
    {
        description = "Property to hold float values in range [0, 10].";
        value = 1.f;
        minValue = 0;
        maxValue = 10.f;
        stepValue = 0.1f;
        
        delegate SliderBox
        {
            fillColor = QColor::fromRgb(170, 170, 255);
        }
    }
```

**Comment by kmkolasinski** [comment]
Wow, its really cool! I will wait for mouse control. BTW: I usually work with AB late at night after work.

**Comment by lexxmark** [comment]
Mouse wheel and mouse single click is implemented.
Mouse drag is on the go.

>BTW: I usually work with AB late at night after work.

I also worked at night but in USA timezone.

**Comment by lexxmark** [comment]
@kmkolasinski and @ppiecuch - I'm finished with SliderBox delegate.
Please test it and if everything is OK - close the issue.

**Comment by kmkolasinski** [comment]
Hi, thanks I'm going to check it right now.

**Comment by kmkolasinski** [comment]
Hi, for me is ok, however I will customize it a little bit to have it like I want ;)
I don't want to bother you anymore in this case, since every person
has his own vision how such button should look like.
I prefer that styl in AwesomeBump :) [slider](https://github.com/kmkolasinski/AwesomeBump/blob/master/Wiki/Tests/guiProp.png)

**Comment by kmkolasinski** [comment]
Hi, I'm trying to override the even implementation for mouse dragging
```
bool QtnPropertyDelegateFloatSlideBox::event(QtnPropertyDelegateEventContext& context, const QtnPropertyDelegateSubItem& item)
{
    switch (context.eventType())
    {
```
but I cannot force it to work with mouse dragging. It seems that all events are blocked if for example mouse is pressed. Do you know how to solve it?

**Comment by lexxmark** [comment]
Hi, does my QtnPropertyDelegateFloatSlideBox class work?
Do you want to customize delegate behavior? It should be pretty much similar as your version.
I only see difference in display (draw function).

It's strange that you have troubles with event function, may be you don't call **trackState()** during sub item creation
```
bool QtnPropertyDelegateFloatSlideBox::createSubItemValueImpl(QtnPropertyDelegateDrawContext&, QtnPropertyDelegateSubItem& subItemValue)
{
    subItemValue.trackState();
    subItemValue.drawHandler = qtnMemFn(this, &QtnPropertyDelegateFloatSlideBox::draw);
    subItemValue.eventHandler = qtnMemFn(this, &QtnPropertyDelegateFloatSlideBox::event);
    return true;
}
```

May be you can just push your code in you fork of QtnProperty, so I will be able pull it and debug.

Anyway I'm planning to generalize this delegate to be basis for all numeric properties Int, Uint, Double, Float. And polish it a bit.
After this you could just grab the code and modify it as you want.

**Comment by lexxmark** [comment]
@kmkolasinski - I've stabilize  QtnPropertyDelegateSlideBox code.
Please try now and in case any problems push your version to your fork of QtnProperty

**Comment by kmkolasinski** [comment]
Hi,
QtnPropertyDelegateFloatSlideBox yes it works :) I copied the  [QtnPropertyDelegateFloatSlideBox](https://github.com/lexxmark/QtnProperty/blob/master/PropertyWidget/Delegates/Core/PropertyDelegateFloat.h#L39) from your repository and created a new files in my project. I wanted to customize Slider behaviour and appearance.  I did it yesterday in the evening but I did not want to push not polished code.
For me it seems that "mouse drag" event (mouse movement + mouse pressed) is not even tracked by event handler - only mouse movement is detected.   
I will try this evening to add, lets hope it will work
```
subItemValue.trackState();
```

**Comment by kmkolasinski** [comment]
Hi, my last anwser is about your question from yesterday :) Not this:
```
@kmkolasinski - I've stabilize QtnPropertyDelegateSlideBox code.
Please try now and in case any problems push your version to your fork of QtnProperty
```

**Comment by kmkolasinski** [comment]
```
Please try now and in case any problems push your version to your fork of QtnProperty
```
I just add one line of QDebug() in the event function to see what kind of events are catched,

**Comment by lexxmark** [comment]
> I copied the QtnPropertyDelegateFloatSlideBox from your repository and created a new files in my project.

Did you copied all other files? There are huge modifications in PropertyDelegate.h/cpp; PropeetyView.h/cpp and other files

>  I did not want to push not polished code

I mean you can "play" with my modifications in you fork of QtnProperty project. It's independent from AB project. So you can easily push and debug code there.

**Comment by kmkolasinski** [comment]
```
Did you copied all other files? There are huge modifications in PropertyDelegate.h/cpp; PropeetyView.h/cpp and other files
```
No I just created separate class file copying the QtnPropertyDelegateSlideBox class which I then called QtnPropertyDelegateABFloatSlider class, the content is exactly the same as QtnPropertyDelegateSlideBox class but I started to play with event method, to see what I can change or not. 
```
I mean you can "play" with my modifications in you fork of QtnProperty project. It's independent from AB project. So you can easily push and debug code there.
```
Yes you are right.

**Comment by lexxmark** [comment]
Now you can find QtnPropertyDelegateSlideBox class in PropertyDelegate.h file.
There are some new Event types in event function:
1. QtnSubItemEvent::Activated - mouse enters slidebox rect
2. QtnSubItemEvent::PressMouse - user pressed mouse button
3. QtnSubItemEvent::ReleaseMouse - user released mouse button -> end edit

**Comment by kmkolasinski** [comment]
Great I will pull the code and try it later ! Thanks!

**Comment by lexxmark** [comment]
OK I'm finished for now.

Just play with new code in [QtnProperty](https://github.com/kmkolasinski/QtnProperty) and push your modifications, so I will be able to help you.

Bye

**Comment by kmkolasinski** [comment]
Ok, thanks again.

**Comment by kmkolasinski** [comment]
OMG, this new one is perfect :) Thanks!
