### ISSUE TITLE
License on Qt Apps says GPL

### ISSUE THREAD

**Issue by jacmoe** [lexxmark/QtnProperty#2]
I almost didn't bother with this project because it says that it's licensed under the GPL on Qt apps :)
However, it was a pleasant surprise to see that the license has changed to Apache.
Could you perhaps change the information?
Thanks!

**Comment by lexxmark** [comment]
Sure. Just updated it.

May be you can advice me which sites is the best place to share information about my project?

Regards,
  Alex
