### ISSUE TITLE
Signals in QtnProperty

### ISSUE THREAD

**Issue by kmkolasinski** [lexxmark/QtnProperty#3]
Hi, 
I want to add QtnProperty to my project in which I  have a set of parameters which control the application. I would like to add the possibility to update the application each time  one of the parameters has changed. Normally, I would write a signal "parameterChanged" for each property and detect this signal in main class. The question is: How can I do it with QtnProperty ?
Thanks in advance.

**Comment by lexxmark** [comment]
Hi Krzysztof,

All properties and property sets QtnProperty have two signals (defined in base class [QtnPropertyBase](https://github.com/lexxmark/QtnProperty/blob/master/Core/PropertyBase.h#L90)) 
```
    void propertyWillChange(const QtnPropertyBase* changedProperty, const QtnPropertyBase* firedProperty, QtnPropertyChangeReason reason, QtnPropertyValuePtr newValue);
    void propertyDidChange(const QtnPropertyBase* changedProperty, const QtnPropertyBase* firedProperty, QtnPropertyChangeReason reason);
```
These signals notify before or after any changes in particular property or property set. The **reason** parameter tells which part of the object has changed. In your case you should check **reason** for **QtnPropertyChangeReasonValue** flag.

Also the signals are propagated  upward in hierarchy of properties. Thus property set containing firing property will also fire its signal. So you can connect to the top level property set's **propertyDidChange** signal to catch changes from any its sub-property. Parameter **changedProperty** is a pointer to the actual changed property and **firedProperty** is a pointer to the property which firing the signal (for example top level property set).

Here is a little example to show main idea (given the property set described in [README](https://github.com/lexxmark/QtnProperty/blob/master/README.md))
```
QtnPropertySetTextEditor params;
QObject::connect(&params, &QtnPropertyBase::propertyDidChange, [] (const QtnPropertyBase* changedProperty, const QtnPropertyBase* firedProperty, QtnPropertyChangeReason reason) {
        if (reason & QtnPropertyChangeReasonValue)
        {
               // any value changes in enableWrapping, replaceTabsWithSpaces,
               // tabSize sub properties will be caught here
        }
    });
```

Regards,
   Alex

**Comment by kmkolasinski** [comment]
Hi Alex, 
Thank you for a quick answer. I've tried your example and it works perfectly. Actually, I was already trying to use slots in such a way:
```
    connect(settings,SIGNAL(propertyDidChange(const QtnPropertyBase*,const QtnPropertyBase*,QtnPropertyChangeReason)),
            this,SLOT(propertiesChanged(const QtnPropertyBase*,const QtnPropertyBase*,QtnPropertyChangeReason)));
```
But it did not work for me, before I wrote to you. Now, I don't know why it started to work, so both solutions are ok. Thanks!

**Comment by lexxmark** [comment]
You are welcome
