### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'release\QtnCoreUnity.obj'

### ISSUE THREAD

**Issue by giladreich** [lexxmark/QtnProperty#30]
> LINK : fatal error LNK1181: cannot open input file 'release\QtnCoreUnity.obj'
> jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Core\Makefile.Release [C:\Users\User\Documents\Visual Studio 2015\Projects\QtnProperty\bin-win\QtnPropertyCore.lib] Error 1181
> jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Core\Makefile [release] Error 2
> jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Makefile [sub-Core-make_first] Error 2
> 17:30:25: The process "C:\Qt\Qt5.8.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
> Error while building/deploying project Property (kit: Desktop Qt 5.8.0 MSVC2015_64bit)
> When executing step "Make"
> 17:30:25: Elapsed time: 00:36.

Hey guys, seems like a great project and would like to use it in mine, but I'm getting this error while trying to compile it.
I'm on Windows 10 64bit, Qt 5.8 with msvc2015_64 also tried on Qt5.8.0-mingw-5-3.
I tried compiling through the Qt Creator and also with cmake. Nmake commands also didn't help. 
Does Qt 5.8 works with this one? or the libraries here needs to be updated?

**Comment by lexxmark** [comment]
I will look into it.

At the first glance "unity build" doesn't work for some reason.
You can try disable unity building by removing line
CONFIG += qtn_unity_build
from Core.pro file.

**Comment by GiladRe** [comment]
@lexxmark Thanks for the tip, but that didn't do the trick unfortunately. 
I tried on release and debug mode and also clean -> run qmake -> build all.
Still getting same logs  but for PropertyBase.obj:
```
12:05:38: Starting: "C:\Qt\Qt5.8.0\Tools\QtCreator\bin\jom.exe" 
	cd Core\ && ( if not exist Makefile C:\Qt\Qt5.8.0\5.8\msvc2015_64\bin\qmake.exe -o Makefile "C:\Users\User\Documents\Visual Studio 2015\Projects\QtnProperty\Core\Core.pro" -spec win32-msvc2015 ) && C:\Qt\Qt5.8.0\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.8.0\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	lib /NOLOGO  /OUT:"C:\Users\User\Documents\Visual Studio 2015\Projects\QtnProperty\bin-win\QtnPropertyCore.lib" @C:\Users\User\AppData\Local\Temp\QtnPropertyCore.lib.10404.375.jom
LINK : fatal error LNK1181: cannot open input file 'release\PropertyBase.obj'
jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Core\Makefile.Release [C:\Users\User\Documents\Visual Studio 2015\Projects\QtnProperty\bin-win\QtnPropertyCore.lib] Error 1181
jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Core\Makefile [release] Error 2
jom: C:\Users\User\Documents\Visual Studio 2015\Projects\build-Property-Desktop_Qt_5_8_0_MSVC2015_64bit-Release\Makefile [sub-Core-make_first] Error 2
12:05:39: The process "C:\Qt\Qt5.8.0\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project Property (kit: Desktop Qt 5.8.0 MSVC2015_64bit)
When executing step "Make"
```

**Comment by lexxmark** [comment]
I'm trying to to reproduce your problem. But it's OK so far.
According to error:

> LINK : fatal error LNK1181: cannot open input file 'release\PropertyBase.obj'

It seems like build system looking for object files in a wrong place.
Could you check where object files are placed and where they are searched during linking?

**Comment by lexxmark** [comment]
I've reproduced the problem. Seems to be specific on Qt 5.8 only.
Trying to fix...

**Comment by lexxmark** [comment]
The problem I faced was related to old QtnProperty code,
after sync with master the problem disappeared.

Please sent full logs of project compilation.
