### ISSUE TITLE
Improved QtnProperties

### ISSUE THREAD

**Issue by lexxmark** [lexxmark/QtnProperty#33]
I've noticed that [https://github.com/kusharami/QtnProperty](https://github.com/kusharami/QtnProperty) has a lot of improvements/refactorings that could be interesting/beneficial for users.

@kusharami May I paste a link to your project in my README.md with a short description of changes/improvements available there?

**Comment by kusharami** [comment]
Hello. Sure you can link my fork. 
Thank you for the original work by the way, it helps me a lot!

List of my features :

- **Multi-properties with QtnMultipleProperty**. It is useful when you want to show properties of multiple objects at once. When values of objects's properties differ it shows grayed **(Multiple properties)**. When you set a new property value, it will be changed in every dependent object. Multi-property set can be created with _qtnCreateQObjectMultiPropertySet_ function defined in [QObjectPropertySet.h](https://github.com/kusharami/QtnProperty/blob/master/QtnProperty/QObjectPropertySet.h) or from custom property sets in a loop with _qtnPropertiesToMultiSet_ function where _target_ argument is a multi-property set, and _source_ argument is a source property set you want to join.
- **QVariant properties with QtnCustomPropertyWidget**. You can edit QVariant as property set / add/remove subproperties in QVariantMap or QVariantList, copy/paste variant properties.
- **Integer 64 properties** QtnPropertyInt64 QtnPropertyUInt64
- **Floating point variants of QPoint, QSize, QRect properties**
- **Overriding QtnPropertyDelegateFactory for QtnPropertySet**
- **Improvements to sync objects values and property editors**
- **Translations EN_RU**
