### ISSUE TITLE
Mouse Movement detection & Drawing rectangle in QtnProperty

### ISSUE THREAD

**Issue by kmkolasinski** [lexxmark/QtnProperty#4]
Hi, 
another question: Is there a possibility to change for example Float property using mouse movement, I was thinking about similar sliders like in gimp 2.8, such that one can change the value with mouse additionaly the property is filled with "progress like" bar rectangle depending on the current, min and max values of given property.
Thanks in advance.

**Comment by lexxmark** [comment]
Sure,

visual appearance and edit widget for any kind of property can be customized using [Delegates](https://github.com/lexxmark/QtnProperty/blob/master/PropertyWidget/Delegates/PropertyDelegate.h#L42). The code quite simple and self evident.

You can see example of using different delegates in [Demo](https://github.com/lexxmark/QtnProperty/blob/master/Demo/Demo.pef#L137) project. Also you can search code for **QtnPropertyDelegateQStringFile** word to figure out how to write your own delegates.

If it still unclear don't hesitate to ask more.

**Comment by kmkolasinski** [comment]
Hi, thanks. I will try those delegates. In case of problem I will contact you.
Best regards.
