### ISSUE TITLE
Improve delegates look&feel

### ISSUE THREAD

**Issue by lexxmark** [lexxmark/QtnProperty#8]
Implement mechanism to notify delegate if mouse over or pushed on the delegate.
For example to make pushing Button's delegate more natural.

**Comment by lexxmark** [comment]
Also recover tooltips for delegates.

**Comment by kmkolasinski** [comment]
It would be nice to have access to Button QPalette, thus I would have possibility to customize everything what I want. Title text alignment should be in center in my opinion.

**Comment by lexxmark** [comment]
@ppiecuch asked to have Button delegate in form of link.
Guys, please decide what is most likely we should have: button view or link view?
And I will implement it after "SlideBox" delegate.

**Comment by ppiecuch** [comment]
Up to Krzysztof :) I am opting for link because few full buttons might make the view quite crowdy (especially on mac, where they could be, for example: blue by default). But this is not a problem for me :)

Btw: this gimp-like "slider" is pretty cool looking.

P.

**Comment by lexxmark** [comment]
OK later I'll make link delegate, so you will be able to play with it and choose

**Comment by kmkolasinski** [comment]
For me any button is ok in AwesomeBump ;) Just wanted to inform that I will answer and test all changes on Monday evening.

**Comment by lexxmark** [comment]
@kmkolasinski  you wrote:
> It would be nice to have access to Button QPalette, thus I would have possibility to customize everything what I want.

Now Button property class has signal:
```
Q_SIGNALS:
    void preDrawButton(const QtnPropertyButton* property, QStyleOptionButton* option);
```

So you can connect to it in C++ code and modify **option** parameter before it will be used to draw button.

@ppiecuch  - I've added link delegate for Button property. So you can try it.
```
    Button ButtonLinkProperty
    {
        clickHandler = [](const QtnPropertyButton* bttn) {
            qDebug() << Q_FUNC_INFO << "Link has clicked: " << bttn;
        };
        
        delegate Link { title = "Click on me"; }
    }
```
