### ISSUE TITLE
Implement "reset value" optional button

### ISSUE THREAD

**Issue by lexxmark** [lexxmark/QtnProperty#9]

**Comment by lexxmark** [comment]
@ppiecuch and @kmkolasinski,

"Reset" button implemented for any property that has [resetCallback](https://github.com/lexxmark/QtnProperty/blob/master/Core/PropertyBase.h#L87) (see Demo):

![image](https://cloud.githubusercontent.com/assets/6108224/12741871/9d9939a6-c93d-11e5-8e33-c954b6972c16.png)

Example of usage in pef files:
```
    ABColor RGBColor
    {
        description = "ABColor property with RGB components";
        value = QColor(123, 150, 10);

        // setup reset callback
        resetCallback = [this](QtnPropertyBase&){
            RGBColor = Qt::green;
        };

        delegate { rgbSubItems = true; }
    }
```

In c++ code:
```
    p.RGBColor.setResetCallback(qtnMemFn(this, &MyClass::resetRGBColor));
...
void MyClass::resetRGBColor(QtnPropertyBase& propertyToReset)
{
    auto colorProperty = qobject_cast<QtnPropertyABColor*>(propertyToReset);
    if (colorProperty)
        colorProperty->setValue(Qt::red);
}
```

**Comment by kmkolasinski** [comment]
Hi, I will test it if I will fix other problems. It will take some time, since I'm quite busy now.

**Comment by lexxmark** [comment]
Hi, please check ResetCallback functionality
